<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>HWWidget</AssemblyName>
    <Version>1.1.1</Version>
    <RootNamespace>HWWidget</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <StartupObject>HWWidget.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="app.ico" LogicalName="app.ico" />
  </ItemGroup>
  <ItemGroup>
    <!-- the installer lives in a subfolder with its own project -->
    <Compile Remove="Setup/**" />
    <None Remove="Setup/**" />
  </ItemGroup>
</Project>
